name: Build V2Ray for iOS ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Download v2ray-core source
        run: git clone https://github.com/v2fly/v2ray-core.git v2ray-core

      - name: Build V2Ray for iOS ARM64
        run: |
          cd v2ray-core
          GOOS=darwin GOARCH=arm64 CGO_ENABLED=1 go build -v -tags json -o v2ray-ios

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: v2ray-ios-arm64
          path: v2ray-core/v2ray-ios
