name: Build V2Ray for iOS ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      CGO_ENABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip golang

      - name: Download v2ray-core source
        run: |
          git clone --recursive https://github.com/v2fly/v2ray-core.git
          cd v2ray-core
          go mod tidy

      - name: Build V2Ray for iOS ARM64
        run: |
          cd v2ray-core
          GOOS=ios GOARCH=arm64 go build -o v2ray-arm64-ios ./main

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: v2ray-arm64-ios
          path: v2ray-core/v2ray-arm64-ios
